spring:
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML5
  datasource:
    url: jdbc:mysql://localhost/melody_blog_db?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: your-password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  mail:
    host:
    port:
    username:
    password:
    properties:
      smtp:
        starttls:
          enable: true
          required: true
        auth: true
      mail:
        smtp:
          ssl:
            enable: true
  messages:
    basename: i18n/messages